name: lint
on:
  - push
  - pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Fix package-lock.json
      run: rm package-lock.json
    - name: Install dependencies
      run: npm i --also=dev
    - name: Run TypeScript compiler (under webpack)
      run: npm run compile
    - name: Run ESLint
      run: npm run eslint